theme: jekyll-theme-primer
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings
exclude:
  - Practice1/
  - Practice2/
  - Practice3/
